export {MainLayout} from './MainLayout/MainLayout'
export {Header} from './Header/Header'
export {Footer} from './Footer/Footer'
export {HeaderMenu} from './HeaderMenu/HeaderMenu'
export {MainContent} from  './MainContent/MainContent'
export {SideBar} from './SideBar/SideBar'
export {ContentBlock} from './ContentBlock/ContentBlock'
export {AdvContent} from './AdvContent/AdvContent'
